apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Node.js Express microservice
  tags:
    - nodejs
    - express
    - backend
spec:
  type: service
  lifecycle: sandbox
  owner: msbx-team